export const exchangeEnglish = {
    who: 'Look who’s here.',
    arrivalEye: 'A familiar face at the doorstep',
    arrivalIntro: 'Before we open the door: which one is you?',
    changeName: 'Choose another name',
    protectedName: 'Your name is protected',
    catSays: 'Prrr. The wrapping paper is mine.',
    name: 'Your name',
    chooseName: 'Choose your name',
    password: 'Password',
    repeat: 'Password, once more',
    protect: 'Choose a password to keep your little secret safe.',
    passwordRules:
        'Use 8–128 characters and at least three of: lowercase letters, uppercase letters, numbers, special characters.',
    signIn: 'Come on in',
    forgot: 'Forgot your password?',
    logout: 'Sign out',
    save: 'Save my wish',
    saving: 'Saving…',
    saved: 'Tucked safely into your notebook.',
    add: 'Write a wish',
    edit: 'Edit this wish',
    remove: 'Remove this wish',
    confirmRemove: 'Remove this note?',
    cancel: 'Keep it',
    yesRemove: 'Yes, remove it',
    empty: 'A little room for wishes.',
    emptyOther: 'No wishes here just yet. A lovely surprise will do, too.',
    previous: 'Previous',
    next: 'Next',
    bought: 'I’m getting this',
    release: 'Put it back',
    claimed: 'Someone has this covered',
    mine: 'You have this covered',
    locked: 'This note is tucked away and cannot be changed.',
    backNotes: 'Back to my notes',
    unknown: 'Your choice may already be saved. Check before choosing again.',
    retryPick: 'Check my choice',
    picking: 'Keeping your choice safe…',
    chosen: 'Your person is',
    seeNotes: 'Open their notes',
    noPerson: 'A little secret is waiting in the tree.',
    choose: 'Visit the tree',
    branch: 'Branch',
    loadMore: 'More notes',
    waiting: 'The house is getting ready.',
    organiser: 'Organiser',
    recovery: 'A fresh key to the house',
    newPassword: 'New password',
    resetPassword: 'Set my new password',
    recovered: 'Your new password is ready. Come back in with your name.',
    reopen: 'Please reopen your private recovery link, or ask the organiser for a new one.',
    mismatch: 'The two passwords do not match yet.',
    recoverHelp: 'Ask the organiser privately for a recovery link.',
    error: 'That did not quite work. Please try again.',
    offline: 'The connection wandered off. Your draft is still here.',
    unavailable:
        'That ornament is no longer available. Another little secret is waiting.',
    protected: 'That name has just been protected. Sign in instead.',
    credentials: 'That password does not open this door.',
    changed: 'This note changed. Please read it again before choosing.',
    expired: 'Please sign in again.',
    impossible: 'These exclusions leave someone without a recipient.',
    setup: 'Prepare the house',
    roster: 'Family names · one per line',
    exclusions: 'Cannot draw',
    saveSetup: 'Save the family',
    validate: 'Check the draw',
    valid: 'Everyone can receive a gift.',
    open: 'Open the house',
    reset: 'Reset the whole season',
    resetHelp:
        'This clears all passwords, draws, wishes and claims. Names become unprotected. Type RESET to confirm.',
    issue: 'Create private recovery link',
    reauth: 'Confirm organiser password',
    copyLink: 'Copy this link privately. A new link replaces the previous one.',
    back: 'Back to the house',
    soundOn: 'Sound on',
    soundOff: 'Sound off',
    page: 'Page',
    link: 'Open gift link',
    noSetup: 'Sign in to prepare this season.',
    busy: 'The house is busy for a moment. Please try again.',
    rate: 'A little pause, please. Try again in a minute.',
    recoveryInvalid:
        'This recovery link has expired or was already used. Ask for a new one.',
    guidelines: 'A few gift ideas',
    reveal: 'One tap, one person. Your choice is final.',
    confirm: 'Save',
    missing: 'Please choose a name and enter your password.',
    retry: 'Try again',
    refresh: 'Refresh notes',
    discard: 'Discard this draft',
    settings: 'Settings',
    destinations: 'Around the house',
};
export type ExchangeCopy = Readonly<typeof exchangeEnglish>;
export const exchangeHungarian: ExchangeCopy = {
    who: 'Ki jött meg?',
    arrivalEye: 'Ismerős arc a küszöbön',
    arrivalIntro: 'Mielőtt ajtót nyitunk: melyik név a tiéd?',
    changeName: 'Másik nevet választok',
    protectedName: 'Jelszóval védett név',
    catSays: 'Mrrr. A csomagolópapír az enyém.',
    name: 'A neved',
    chooseName: 'Válaszd ki a neved',
    password: 'Jelszó',
    repeat: 'Jelszó még egyszer',
    protect: 'Válassz jelszót a kis titkodhoz.',
    passwordRules:
        '8–128 karakter, és legalább három ezek közül: kisbetű, nagybetű, szám, speciális karakter.',
    signIn: 'Gyere be',
    forgot: 'Elfelejtetted a jelszavad?',
    logout: 'Kilépés',
    save: 'Elteszem a kívánságom',
    saving: 'Mentés…',
    saved: 'Biztonságban a füzetedben.',
    add: 'Új kívánság',
    edit: 'Szerkesztés',
    remove: 'Kívánság törlése',
    confirmRemove: 'Töröljük ezt a lapot?',
    cancel: 'Mégsem',
    yesRemove: 'Igen, törlöm',
    empty: 'Itt a helye a kívánságaidnak.',
    emptyOther: 'Még nincs itt kívánság. Egy kedves meglepetés is jól jöhet.',
    previous: 'Előző',
    next: 'Következő',
    bought: 'Ezt én szerzem be',
    release: 'Mégsem én veszem',
    claimed: 'Erről már gondoskodik valaki',
    mine: 'Erről te gondoskodsz',
    locked: 'Ez a kívánság már nem módosítható.',
    backNotes: 'Vissza a lapjaimhoz',
    unknown:
        'Lehet, hogy már elmentettük a választásod. Ellenőrizzük, mielőtt újra választasz.',
    retryPick: 'Választás ellenőrzése',
    picking: 'Biztonságba helyezzük a választásod…',
    chosen: 'Őt ajándékozod meg:',
    seeNotes: 'Megnézem a kívánságait',
    noPerson: 'Egy kis titok vár a fán.',
    choose: 'Irány a fa',
    branch: 'Ág',
    loadMore: 'További lapok',
    waiting: 'Még készülődik a házikó.',
    organiser: 'Szervező',
    recovery: 'Új kulcs a házikóhoz',
    newPassword: 'Új jelszó',
    resetPassword: 'Új jelszó mentése',
    recovered: 'Kész az új jelszavad. Most már beléphetsz a neveddel.',
    reopen: 'Nyisd meg újra a privát helyreállítási linket, vagy kérj újat a szervezőtől.',
    mismatch: 'A két jelszó még nem egyezik.',
    recoverHelp: 'Kérj privát üzenetben helyreállítási linket a szervezőtől.',
    error: 'Ez most nem sikerült. Próbáld meg újra.',
    offline: 'Elkalandozott a kapcsolat. A piszkozatod megvár.',
    unavailable: 'Ez a dísz már nem választható. Egy másik kis titok vár rád.',
    protected: 'Ezt a nevet közben már levédték. Lépj be a jelszóval.',
    credentials: 'Ez a jelszó nem nyitja az ajtót.',
    changed: 'Ez a lap közben megváltozott. Olvasd el újra a választás előtt.',
    expired: 'Kérlek, lépj be újra.',
    impossible: 'Ezekkel a kizárásokkal valakinek nem jutna név.',
    setup: 'Készítsük elő a házikót',
    roster: 'Családtagok · soronként egy név',
    exclusions: 'Nem húzhatja',
    saveSetup: 'Család mentése',
    validate: 'Húzás ellenőrzése',
    valid: 'Mindenkinek juthat ajándék.',
    open: 'Házikó megnyitása',
    reset: 'Teljes szezon visszaállítása',
    resetHelp:
        'Minden jelszó, húzás, kívánság és foglalás törlődik. A nevek újra szabadok lesznek. Megerősítéshez írd be: RESET',
    issue: 'Privát helyreállítási link',
    reauth: 'Szervezői jelszó megerősítése',
    copyLink:
        'Ezt a linket privát üzenetben küldd el. Az új link érvényteleníti az előzőt.',
    back: 'Vissza a házikóhoz',
    soundOn: 'Hang be',
    soundOff: 'Hang ki',
    page: 'Oldal',
    link: 'Ajándék linkje',
    noSetup: 'Lépj be a szezon előkészítéséhez.',
    busy: 'Egy pillanatra elfoglalt a házikó. Próbáld újra.',
    rate: 'Egy kis türelmet kérünk. Próbáld újra egy perc múlva.',
    recoveryInvalid: 'Ez a link lejárt vagy már felhasználták. Kérj újat.',
    guidelines: 'Néhány ajándékötlet',
    reveal: 'Egy érintés, egy név. A választásod végleges.',
    confirm: 'Mentés',
    missing: 'Válassz nevet, és add meg a jelszót.',
    retry: 'Újra',
    refresh: 'Kívánságok frissítése',
    discard: 'Piszkozat elvetése',
    settings: 'Beállítások',
    destinations: 'A házikóban',
};
export const exchangeError = (code: string, copy: ExchangeCopy): string => {
    const messages = new Map([
        ['OFFLINE', copy.offline],
        ['OPTION_UNAVAILABLE', copy.unavailable],
        ['NAME_ALREADY_PROTECTED', copy.protected],
        ['INVALID_CREDENTIALS', copy.credentials],
        ['CONTENT_CHANGED', copy.changed],
        ['WISH_LOCKED', copy.locked],
        ['CLAIM_UNAVAILABLE', copy.claimed],
        ['UNAUTHENTICATED', copy.expired],
        ['SEASON_CHANGED', copy.expired],
        ['IMPOSSIBLE_DRAW', copy.impossible],
        ['BUSY', copy.busy],
        ['RATE_LIMITED', copy.rate],
        ['RECOVERY_INVALID', copy.recoveryInvalid],
    ]);
    return code ? (messages.get(code) ?? copy.error) : '';
};
